# Generated by Django 5.1.15 on 2026-07-23 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('title_fr', models.CharField(max_length=200, null=True, verbose_name='Titre')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Titre')),
                ('title_ar', models.CharField(max_length=200, null=True, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('slug_fr', models.SlugField(max_length=200, null=True, unique=True, verbose_name='Slug')),
                ('slug_en', models.SlugField(max_length=200, null=True, unique=True, verbose_name='Slug')),
                ('slug_ar', models.SlugField(max_length=200, null=True, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(help_text='Résumé affiché dans les cartes (max 300 caractères)', max_length=300, verbose_name='Description courte')),
                ('short_description_fr', models.TextField(help_text='Résumé affiché dans les cartes (max 300 caractères)', max_length=300, null=True, verbose_name='Description courte')),
                ('short_description_en', models.TextField(help_text='Résumé affiché dans les cartes (max 300 caractères)', max_length=300, null=True, verbose_name='Description courte')),
                ('short_description_ar', models.TextField(help_text='Résumé affiché dans les cartes (max 300 caractères)', max_length=300, null=True, verbose_name='Description courte')),
                ('full_description', models.TextField(verbose_name='Description complète')),
                ('full_description_fr', models.TextField(null=True, verbose_name='Description complète')),
                ('full_description_en', models.TextField(null=True, verbose_name='Description complète')),
                ('full_description_ar', models.TextField(null=True, verbose_name='Description complète')),
                ('icon', models.CharField(blank=True, help_text="Classe d'icône ou emoji", max_length=100, verbose_name='Icône')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Image principale')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/gallery/', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, max_length=300, verbose_name='Texte alternatif')),
                ('alt_text_fr', models.CharField(blank=True, max_length=300, null=True, verbose_name='Texte alternatif')),
                ('alt_text_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='Texte alternatif')),
                ('alt_text_ar', models.CharField(blank=True, max_length=300, null=True, verbose_name='Texte alternatif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='services.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Image du service',
                'verbose_name_plural': 'Images du service',
                'ordering': ['order'],
            },
        ),
    ]
