# Generated by Django 5.1.15 on 2026-09-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Description pour les moteurs de recherche (max 160 caractères). Laisser vide pour utiliser la description courte.', max_length=160, verbose_name='Description SEO'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_description_ar',
            field=models.CharField(blank=True, help_text='Description pour les moteurs de recherche (max 160 caractères). Laisser vide pour utiliser la description courte.', max_length=160, null=True, verbose_name='Description SEO'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_description_en',
            field=models.CharField(blank=True, help_text='Description pour les moteurs de recherche (max 160 caractères). Laisser vide pour utiliser la description courte.', max_length=160, null=True, verbose_name='Description SEO'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_description_fr',
            field=models.CharField(blank=True, help_text='Description pour les moteurs de recherche (max 160 caractères). Laisser vide pour utiliser la description courte.', max_length=160, null=True, verbose_name='Description SEO'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Titre pour les moteurs de recherche (max 70 caractères). Laisser vide pour utiliser le titre du service.', max_length=70, verbose_name='Titre SEO'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_title_ar',
            field=models.CharField(blank=True, help_text='Titre pour les moteurs de recherche (max 70 caractères). Laisser vide pour utiliser le titre du service.', max_length=70, null=True, verbose_name='Titre SEO'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='Titre pour les moteurs de recherche (max 70 caractères). Laisser vide pour utiliser le titre du service.', max_length=70, null=True, verbose_name='Titre SEO'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_title_fr',
            field=models.CharField(blank=True, help_text='Titre pour les moteurs de recherche (max 70 caractères). Laisser vide pour utiliser le titre du service.', max_length=70, null=True, verbose_name='Titre SEO'),
        ),
    ]
