# Generated by Django 5.1.15 on 2026-07-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('title_fr', models.CharField(max_length=200, null=True, verbose_name='Titre')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Titre')),
                ('title_ar', models.CharField(max_length=200, null=True, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_fr', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('description_ar', models.TextField(null=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icône CSS')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Étape du processus',
                'verbose_name_plural': 'Étapes du processus',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='VR Creation Company', max_length=200, verbose_name='Nom du site')),
                ('site_name_fr', models.CharField(default='VR Creation Company', max_length=200, null=True, verbose_name='Nom du site')),
                ('site_name_en', models.CharField(default='VR Creation Company', max_length=200, null=True, verbose_name='Nom du site')),
                ('site_name_ar', models.CharField(default='VR Creation Company', max_length=200, null=True, verbose_name='Nom du site')),
                ('tagline', models.CharField(default="L'innovation en action", max_length=300, verbose_name='Slogan')),
                ('tagline_fr', models.CharField(default="L'innovation en action", max_length=300, null=True, verbose_name='Slogan')),
                ('tagline_en', models.CharField(default="L'innovation en action", max_length=300, null=True, verbose_name='Slogan')),
                ('tagline_ar', models.CharField(default="L'innovation en action", max_length=300, null=True, verbose_name='Slogan')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Favicon')),
                ('email', models.EmailField(default='contact@vrcreation.com', max_length=254, verbose_name='Email de contact')),
                ('phone', models.CharField(blank=True, default='+33 1 23 45 67 89', max_length=30, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, default='Paris, France', verbose_name='Adresse')),
                ('address_fr', models.TextField(blank=True, default='Paris, France', null=True, verbose_name='Adresse')),
                ('address_en', models.TextField(blank=True, default='Paris, France', null=True, verbose_name='Adresse')),
                ('address_ar', models.TextField(blank=True, default='Paris, France', null=True, verbose_name='Adresse')),
                ('google_analytics_id', models.CharField(blank=True, help_text='Ex: G-XXXXXXXXXX. Chargé uniquement après consentement cookies.', max_length=30, verbose_name='Google Analytics ID')),
                ('social_facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('social_instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('social_linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('social_youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('social_twitter', models.URLField(blank=True, verbose_name='Twitter / X')),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('title_fr', models.CharField(max_length=200, null=True, verbose_name='Titre')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Titre')),
                ('title_ar', models.CharField(max_length=200, null=True, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icône CSS')),
                ('stat_number', models.CharField(blank=True, help_text='Ex: 150+, 98%, 10 ans', max_length=50, verbose_name='Chiffre clé')),
                ('stat_number_fr', models.CharField(blank=True, help_text='Ex: 150+, 98%, 10 ans', max_length=50, null=True, verbose_name='Chiffre clé')),
                ('stat_number_en', models.CharField(blank=True, help_text='Ex: 150+, 98%, 10 ans', max_length=50, null=True, verbose_name='Chiffre clé')),
                ('stat_number_ar', models.CharField(blank=True, help_text='Ex: 150+, 98%, 10 ans', max_length=50, null=True, verbose_name='Chiffre clé')),
                ('stat_label', models.CharField(blank=True, max_length=200, verbose_name='Label du chiffre')),
                ('stat_label_fr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Label du chiffre')),
                ('stat_label_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Label du chiffre')),
                ('stat_label_ar', models.CharField(blank=True, max_length=200, null=True, verbose_name='Label du chiffre')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Point fort',
                'verbose_name_plural': 'Points forts',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('name_fr', models.CharField(max_length=200, null=True, verbose_name='Nom')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Nom')),
                ('name_ar', models.CharField(max_length=200, null=True, verbose_name='Nom')),
                ('role', models.CharField(max_length=200, verbose_name='Rôle')),
                ('role_fr', models.CharField(max_length=200, null=True, verbose_name='Rôle')),
                ('role_en', models.CharField(max_length=200, null=True, verbose_name='Rôle')),
                ('role_ar', models.CharField(max_length=200, null=True, verbose_name='Rôle')),
                ('bio', models.TextField(blank=True, verbose_name='Biographie')),
                ('bio_fr', models.TextField(blank=True, null=True, verbose_name='Biographie')),
                ('bio_en', models.TextField(blank=True, null=True, verbose_name='Biographie')),
                ('bio_ar', models.TextField(blank=True, null=True, verbose_name='Biographie')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Photo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': "Membre de l'équipe",
                'verbose_name_plural': "Membres de l'équipe",
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('title_fr', models.CharField(max_length=200, null=True, verbose_name='Titre')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Titre')),
                ('title_ar', models.CharField(max_length=200, null=True, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_fr', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('description_ar', models.TextField(null=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text="Classe d'icône (ex: fas fa-lightbulb) ou emoji", max_length=100, verbose_name='Icône CSS')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Valeur',
                'verbose_name_plural': 'Valeurs',
                'ordering': ['order'],
            },
        ),
    ]
