# Generated by Django 5.1.15 on 2026-07-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Image page À propos'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.CharField(blank=True, default='© 2026 VR Creation Company', max_length=300, verbose_name='Texte copyright'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text_ar',
            field=models.CharField(blank=True, default='© 2026 VR Creation Company', max_length=300, null=True, verbose_name='Texte copyright'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text_en',
            field=models.CharField(blank=True, default='© 2026 VR Creation Company', max_length=300, null=True, verbose_name='Texte copyright'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text_fr',
            field=models.CharField(blank=True, default='© 2026 VR Creation Company', max_length=300, null=True, verbose_name='Texte copyright'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_og_image',
            field=models.ImageField(blank=True, help_text='Image par défaut pour le partage social (1200x630px recommandé)', null=True, upload_to='site/', verbose_name='Image OG par défaut'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text',
            field=models.TextField(blank=True, default='Nous allions esthétique et technologie de pointe pour transformer vos projets en expériences visuelles immersives et inoubliables.', verbose_name='Texte du pied de page'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_ar',
            field=models.TextField(blank=True, default='Nous allions esthétique et technologie de pointe pour transformer vos projets en expériences visuelles immersives et inoubliables.', null=True, verbose_name='Texte du pied de page'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_en',
            field=models.TextField(blank=True, default='Nous allions esthétique et technologie de pointe pour transformer vos projets en expériences visuelles immersives et inoubliables.', null=True, verbose_name='Texte du pied de page'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_fr',
            field=models.TextField(blank=True, default='Nous allions esthétique et technologie de pointe pour transformer vos projets en expériences visuelles immersives et inoubliables.', null=True, verbose_name='Texte du pied de page'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_maps_embed_url',
            field=models.CharField(blank=True, help_text='URL iframe Google Maps pour la page contact', max_length=500, verbose_name='URL Google Maps (embed)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_search_console_id',
            field=models.CharField(blank=True, help_text='Code de vérification Google Search Console (contenu de la balise meta)', max_length=100, verbose_name='Google Search Console'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, help_text="Image de fond du hero de la page d'accueil", null=True, upload_to='site/', verbose_name='Image hero accueil'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_behance',
            field=models.URLField(blank=True, verbose_name='Behance'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_tiktok',
            field=models.URLField(blank=True, verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_whatsapp',
            field=models.CharField(blank=True, help_text='Numéro WhatsApp au format international (ex: +33612345678)', max_length=30, verbose_name='WhatsApp'),
        ),
    ]
