# Generated by Django 5.1.15 on 2026-07-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_about_image_sitesettings_copyright_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('title_fr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre')),
                ('title_ar', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Diapositive Hero',
                'verbose_name_plural': 'Diapositives Hero',
                'ordering': ['order'],
            },
        ),
    ]
