# Generated by Django 5.1.15 on 2026-07-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_heroslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_video',
            field=models.FileField(blank=True, help_text='Vidéo de fond (MP4, WebM) ou fichier 3D affichée derrière les titres de toutes les pages. Recommandé : MP4, max 15 Mo, 1920x1080.', null=True, upload_to='site/hero/', verbose_name='Vidéo / 3D hero (toutes les pages)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_video_poster',
            field=models.ImageField(blank=True, help_text='Image affichée pendant le chargement de la vidéo hero (1920x600 recommandé)', null=True, upload_to='site/hero/', verbose_name='Image poster vidéo hero'),
        ),
    ]
