# Generated by Django 5.1.15 on 2026-08-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_hero_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_cta1_label',
            field=models.CharField(blank=True, default='Découvrir nos solutions', max_length=100, verbose_name='Bouton hero 1 — libellé'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_cta1_label_ar',
            field=models.CharField(blank=True, default='Découvrir nos solutions', max_length=100, null=True, verbose_name='Bouton hero 1 — libellé'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_cta1_label_en',
            field=models.CharField(blank=True, default='Découvrir nos solutions', max_length=100, null=True, verbose_name='Bouton hero 1 — libellé'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_cta1_label_fr',
            field=models.CharField(blank=True, default='Découvrir nos solutions', max_length=100, null=True, verbose_name='Bouton hero 1 — libellé'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_cta1_link',
            field=models.CharField(blank=True, default='#services', help_text='URL ou ancre (ex: #services, /contact/)', max_length=300, verbose_name='Bouton hero 1 — lien'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_cta2_label',
            field=models.CharField(blank=True, default='Nous contacter', max_length=100, verbose_name='Bouton hero 2 — libellé'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_cta2_label_ar',
            field=models.CharField(blank=True, default='Nous contacter', max_length=100, null=True, verbose_name='Bouton hero 2 — libellé'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_cta2_label_en',
            field=models.CharField(blank=True, default='Nous contacter', max_length=100, null=True, verbose_name='Bouton hero 2 — libellé'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_cta2_label_fr',
            field=models.CharField(blank=True, default='Nous contacter', max_length=100, null=True, verbose_name='Bouton hero 2 — libellé'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_cta2_link',
            field=models.CharField(blank=True, default='/contact/', help_text='URL ou ancre (ex: /contact/)', max_length=300, verbose_name='Bouton hero 2 — lien'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_headline',
            field=models.CharField(blank=True, default='DONNEZ VIE À VOTRE PROJET IMMOBILIER, AVANT MÊME SA CONSTRUCTION.', help_text="Titre principal affiché sur le hero de la page d'accueil", max_length=300, verbose_name='Titre hero accueil'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_headline_ar',
            field=models.CharField(blank=True, default='DONNEZ VIE À VOTRE PROJET IMMOBILIER, AVANT MÊME SA CONSTRUCTION.', help_text="Titre principal affiché sur le hero de la page d'accueil", max_length=300, null=True, verbose_name='Titre hero accueil'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_headline_en',
            field=models.CharField(blank=True, default='DONNEZ VIE À VOTRE PROJET IMMOBILIER, AVANT MÊME SA CONSTRUCTION.', help_text="Titre principal affiché sur le hero de la page d'accueil", max_length=300, null=True, verbose_name='Titre hero accueil'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_headline_fr',
            field=models.CharField(blank=True, default='DONNEZ VIE À VOTRE PROJET IMMOBILIER, AVANT MÊME SA CONSTRUCTION.', help_text="Titre principal affiché sur le hero de la page d'accueil", max_length=300, null=True, verbose_name='Titre hero accueil'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subheadline',
            field=models.TextField(blank=True, default='De la conception 3D à la commercialisation digitale, nous transformons vos projets immobiliers en expériences visuelles capables de séduire, convaincre et générer des prospects.', help_text='Texte affiché sous le titre du hero', verbose_name='Sous-titre hero accueil'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subheadline_ar',
            field=models.TextField(blank=True, default='De la conception 3D à la commercialisation digitale, nous transformons vos projets immobiliers en expériences visuelles capables de séduire, convaincre et générer des prospects.', help_text='Texte affiché sous le titre du hero', null=True, verbose_name='Sous-titre hero accueil'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subheadline_en',
            field=models.TextField(blank=True, default='De la conception 3D à la commercialisation digitale, nous transformons vos projets immobiliers en expériences visuelles capables de séduire, convaincre et générer des prospects.', help_text='Texte affiché sous le titre du hero', null=True, verbose_name='Sous-titre hero accueil'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subheadline_fr',
            field=models.TextField(blank=True, default='De la conception 3D à la commercialisation digitale, nous transformons vos projets immobiliers en expériences visuelles capables de séduire, convaincre et générer des prospects.', help_text='Texte affiché sous le titre du hero', null=True, verbose_name='Sous-titre hero accueil'),
        ),
    ]
