# Generated by Django 5.1.15 on 2026-08-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_hero_homepage_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategicSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('title_fr', models.CharField(max_length=200, null=True, verbose_name='Titre')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Titre')),
                ('title_ar', models.CharField(max_length=200, null=True, verbose_name='Titre')),
                ('importance', models.CharField(help_text="Ex: Les acheteurs veulent se projeter avant d'investir.", max_length=300, verbose_name='Importance du service')),
                ('importance_fr', models.CharField(help_text="Ex: Les acheteurs veulent se projeter avant d'investir.", max_length=300, null=True, verbose_name='Importance du service')),
                ('importance_en', models.CharField(help_text="Ex: Les acheteurs veulent se projeter avant d'investir.", max_length=300, null=True, verbose_name='Importance du service')),
                ('importance_ar', models.CharField(help_text="Ex: Les acheteurs veulent se projeter avant d'investir.", max_length=300, null=True, verbose_name='Importance du service')),
                ('image', models.ImageField(blank=True, help_text='Image affichée sur la carte. Stockée dans le dossier media/services/', null=True, upload_to='services/', verbose_name='Image')),
                ('icon', models.CharField(blank=True, default='fas fa-cube', help_text="Classe d'icône CSS (ex: fas fa-store)", max_length=100, verbose_name='Icône')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Succès stratégique',
                'verbose_name_plural': 'Succès stratégiques',
                'ordering': ['order', 'title'],
            },
        ),
    ]
