# Generated by Django 5.1.15 on 2026-08-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_strategic_success_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='strength',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='strengths/', verbose_name='Image de fond'),
        ),
    ]
