# Generated by Django 5.1.15 on 2026-08-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_promotion_promotioncomparison_promotiondeliverable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='slug_ar',
            field=models.SlugField(max_length=200, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='slug_en',
            field=models.SlugField(max_length=200, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='slug_fr',
            field=models.SlugField(max_length=200, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
