# Generated by Django 5.1.15 on 2026-08-14 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_promotion_slug_ar_promotion_slug_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='slug_ar',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='slug_fr',
        ),
    ]
