# Generated by Django 5.1.15 on 2026-09-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_promotion_slug_ar_remove_promotion_slug_en_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='commission_rate',
            field=models.CharField(blank=True, help_text='Ex: 10%, 15%, ou "Sur négociation". Affiché uniquement pour les offres sur commission.', max_length=50, verbose_name='Taux de commission'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='commission_rate_ar',
            field=models.CharField(blank=True, help_text='Ex: 10%, 15%, ou "Sur négociation". Affiché uniquement pour les offres sur commission.', max_length=50, null=True, verbose_name='Taux de commission'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='commission_rate_en',
            field=models.CharField(blank=True, help_text='Ex: 10%, 15%, ou "Sur négociation". Affiché uniquement pour les offres sur commission.', max_length=50, null=True, verbose_name='Taux de commission'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='commission_rate_fr',
            field=models.CharField(blank=True, help_text='Ex: 10%, 15%, ou "Sur négociation". Affiché uniquement pour les offres sur commission.', max_length=50, null=True, verbose_name='Taux de commission'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='included_services',
            field=models.ManyToManyField(blank=True, help_text='Services inclus dans ce pack. Pour les packs personnalisables, ces services sont pré-cochés.', related_name='promotions', to='services.service', verbose_name='Services inclus'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='is_customizable',
            field=models.BooleanField(default=True, help_text='Si coché, le client peut personnaliser les services inclus. Décocher pour les offres sur commission où VR Creation décide de la stratégie.', verbose_name='Personnalisable'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Cocher pour afficher ce pack en section vedette sur la page d'accueil et d'autres pages.", verbose_name='Mise en avant'),
        ),
    ]
