# Generated by Django 5.1.15 on 2026-09-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_promotion_commission_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotiondeliverable',
            name='image',
            field=models.ImageField(blank=True, help_text='Image optionnelle affichée sur la carte de cette prestation (400x300px recommandé)', null=True, upload_to='promotions/deliverables/', verbose_name='Image / Illustration'),
        ),
    ]
