# Generated by Django 5.1.15 on 2026-09-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_promotiondeliverable_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='video',
            field=models.FileField(blank=True, help_text='Vidéo MP4 expliquant le pack (max 50 Mo). Affichée sur la page du pack si présente.', null=True, upload_to='promotions/videos/', verbose_name='Vidéo explicative du pack'),
        ),
    ]
