# Generated by Django 5.1.15 on 2026-09-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_update_hero_and_seo_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, default='Avenue Ibn Tachfine, bureaux Ibn Battouta, Tanger, Maroc', verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address_ar',
            field=models.TextField(blank=True, default='Avenue Ibn Tachfine, bureaux Ibn Battouta, Tanger, Maroc', null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address_en',
            field=models.TextField(blank=True, default='Avenue Ibn Tachfine, bureaux Ibn Battouta, Tanger, Maroc', null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address_fr',
            field=models.TextField(blank=True, default='Avenue Ibn Tachfine, bureaux Ibn Battouta, Tanger, Maroc', null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='Vrcreation.company@gmail.com', max_length=254, verbose_name='Email de contact'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_cta1_label',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Bouton hero 1 — libellé'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_cta1_label_ar',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Bouton hero 1 — libellé'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_cta1_label_en',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Bouton hero 1 — libellé'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_cta1_label_fr',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Bouton hero 1 — libellé'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_cta2_label',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Bouton hero 2 — libellé'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_cta2_label_ar',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Bouton hero 2 — libellé'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_cta2_label_en',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Bouton hero 2 — libellé'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_cta2_label_fr',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Bouton hero 2 — libellé'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_headline',
            field=models.CharField(blank=True, default='', help_text="Titre principal affiché sur le hero de la page d'accueil", max_length=300, verbose_name='Titre hero accueil'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_headline_ar',
            field=models.CharField(blank=True, default='', help_text="Titre principal affiché sur le hero de la page d'accueil", max_length=300, null=True, verbose_name='Titre hero accueil'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_headline_en',
            field=models.CharField(blank=True, default='', help_text="Titre principal affiché sur le hero de la page d'accueil", max_length=300, null=True, verbose_name='Titre hero accueil'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_headline_fr',
            field=models.CharField(blank=True, default='', help_text="Titre principal affiché sur le hero de la page d'accueil", max_length=300, null=True, verbose_name='Titre hero accueil'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subheadline',
            field=models.TextField(blank=True, default='', help_text='Texte affiché sous le titre du hero', verbose_name='Sous-titre hero accueil'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subheadline_ar',
            field=models.TextField(blank=True, default='', help_text='Texte affiché sous le titre du hero', null=True, verbose_name='Sous-titre hero accueil'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subheadline_en',
            field=models.TextField(blank=True, default='', help_text='Texte affiché sous le titre du hero', null=True, verbose_name='Sous-titre hero accueil'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subheadline_fr',
            field=models.TextField(blank=True, default='', help_text='Texte affiché sous le titre du hero', null=True, verbose_name='Sous-titre hero accueil'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, default='+212634017762', max_length=30, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Slogan'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline_ar',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Slogan'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline_en',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Slogan'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline_fr',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Slogan'),
        ),
    ]
