# Generated by Django 5.1.15 on 2026-07-23 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('name_fr', models.CharField(max_length=200, null=True, verbose_name='Nom')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Nom')),
                ('name_ar', models.CharField(max_length=200, null=True, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('slug_fr', models.SlugField(max_length=200, null=True, unique=True, verbose_name='Slug')),
                ('slug_en', models.SlugField(max_length=200, null=True, unique=True, verbose_name='Slug')),
                ('slug_ar', models.SlugField(max_length=200, null=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titre')),
                ('title_fr', models.CharField(max_length=300, null=True, verbose_name='Titre')),
                ('title_en', models.CharField(max_length=300, null=True, verbose_name='Titre')),
                ('title_ar', models.CharField(max_length=300, null=True, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='Slug')),
                ('slug_fr', models.SlugField(max_length=300, null=True, unique=True, verbose_name='Slug')),
                ('slug_en', models.SlugField(max_length=300, null=True, unique=True, verbose_name='Slug')),
                ('slug_ar', models.SlugField(max_length=300, null=True, unique=True, verbose_name='Slug')),
                ('author', models.CharField(default='VR Creation', max_length=200, verbose_name='Auteur')),
                ('author_fr', models.CharField(default='VR Creation', max_length=200, null=True, verbose_name='Auteur')),
                ('author_en', models.CharField(default='VR Creation', max_length=200, null=True, verbose_name='Auteur')),
                ('author_ar', models.CharField(default='VR Creation', max_length=200, null=True, verbose_name='Auteur')),
                ('excerpt', models.TextField(help_text="Résumé de l'article (max 500 caractères)", max_length=500, verbose_name='Extrait')),
                ('excerpt_fr', models.TextField(help_text="Résumé de l'article (max 500 caractères)", max_length=500, null=True, verbose_name='Extrait')),
                ('excerpt_en', models.TextField(help_text="Résumé de l'article (max 500 caractères)", max_length=500, null=True, verbose_name='Extrait')),
                ('excerpt_ar', models.TextField(help_text="Résumé de l'article (max 500 caractères)", max_length=500, null=True, verbose_name='Extrait')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('content_fr', models.TextField(null=True, verbose_name='Contenu')),
                ('content_en', models.TextField(null=True, verbose_name='Contenu')),
                ('content_ar', models.TextField(null=True, verbose_name='Contenu')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Image principale')),
                ('published_date', models.DateTimeField(verbose_name='Date de publication')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('reading_time', models.PositiveIntegerField(default=5, verbose_name='Temps de lecture (min)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_date'],
            },
        ),
    ]
