# Generated by Django 5.1.15 on 2026-09-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ai_generated',
            field=models.BooleanField(default=False, verbose_name='Généré par IA'),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], default='draft', max_length=20, verbose_name='Statut'),
        ),
    ]
