# Generated by Django 5.1.15 on 2026-07-23 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_identifier', models.SlugField(help_text='Identifiant unique : home, about, services, portfolio, contact, blog, etc.', max_length=100, unique=True, verbose_name='Identifiant de page')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Titre SEO')),
                ('meta_title_fr', models.CharField(blank=True, max_length=70, null=True, verbose_name='Titre SEO')),
                ('meta_title_en', models.CharField(blank=True, max_length=70, null=True, verbose_name='Titre SEO')),
                ('meta_title_ar', models.CharField(blank=True, max_length=70, null=True, verbose_name='Titre SEO')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Description SEO')),
                ('meta_description_fr', models.CharField(blank=True, max_length=160, null=True, verbose_name='Description SEO')),
                ('meta_description_en', models.CharField(blank=True, max_length=160, null=True, verbose_name='Description SEO')),
                ('meta_description_ar', models.CharField(blank=True, max_length=160, null=True, verbose_name='Description SEO')),
                ('og_image', models.ImageField(blank=True, help_text='Image 1200x630px recommandée', null=True, upload_to='seo/', verbose_name='Image Open Graph')),
                ('canonical_url', models.URLField(blank=True, verbose_name='URL canonique')),
                ('no_index', models.BooleanField(default=False, help_text='Ajouter noindex à cette page', verbose_name='Ne pas indexer')),
            ],
            options={
                'verbose_name': 'SEO — Page statique',
                'verbose_name_plural': 'SEO — Pages statiques',
            },
        ),
        migrations.CreateModel(
            name='SEOMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID objet')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Titre SEO')),
                ('meta_title_fr', models.CharField(blank=True, max_length=70, null=True, verbose_name='Titre SEO')),
                ('meta_title_en', models.CharField(blank=True, max_length=70, null=True, verbose_name='Titre SEO')),
                ('meta_title_ar', models.CharField(blank=True, max_length=70, null=True, verbose_name='Titre SEO')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Description SEO')),
                ('meta_description_fr', models.CharField(blank=True, max_length=160, null=True, verbose_name='Description SEO')),
                ('meta_description_en', models.CharField(blank=True, max_length=160, null=True, verbose_name='Description SEO')),
                ('meta_description_ar', models.CharField(blank=True, max_length=160, null=True, verbose_name='Description SEO')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/', verbose_name='Image Open Graph')),
                ('canonical_url', models.URLField(blank=True, verbose_name='URL canonique')),
                ('no_index', models.BooleanField(default=False, verbose_name='Ne pas indexer')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Type de contenu')),
            ],
            options={
                'verbose_name': 'SEO — Métadonnées objet',
                'verbose_name_plural': 'SEO — Métadonnées objets',
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
