# Generated by Django 5.1.15 on 2026-09-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageseo',
            name='keywords',
            field=models.TextField(blank=True, help_text='Mots-clés séparés par des virgules pour cette page (ex: modélisation 3D Tanger, visite virtuelle Maroc)', verbose_name='Mots-clés'),
        ),
        migrations.AddField(
            model_name='pageseo',
            name='keywords_ar',
            field=models.TextField(blank=True, help_text='Mots-clés séparés par des virgules pour cette page (ex: modélisation 3D Tanger, visite virtuelle Maroc)', null=True, verbose_name='Mots-clés'),
        ),
        migrations.AddField(
            model_name='pageseo',
            name='keywords_en',
            field=models.TextField(blank=True, help_text='Mots-clés séparés par des virgules pour cette page (ex: modélisation 3D Tanger, visite virtuelle Maroc)', null=True, verbose_name='Mots-clés'),
        ),
        migrations.AddField(
            model_name='pageseo',
            name='keywords_fr',
            field=models.TextField(blank=True, help_text='Mots-clés séparés par des virgules pour cette page (ex: modélisation 3D Tanger, visite virtuelle Maroc)', null=True, verbose_name='Mots-clés'),
        ),
    ]
